### ISSUE TITLE
ロードが長い問題

### ISSUE THREAD

**Issue by noMA-4** [hayao-serene/serene-startdash#4]
![A0FC3090-DDB5-4B0C-84AF-4C81CA966128](https://user-images.githubusercontent.com/48173871/73587060-dfc50d00-44f9-11ea-8c94-d2911dd8b8b7.jpeg)
上記の通りです。

**Comment by mikity314** [comment]
こればかりはどうしようもない...

**Comment by noMA-4** [comment]
https://github.com/hayao-serene/serene-startdash/pull/5
これによって解決しました。
